---
title: "Replication of Predicting the Present with Google Trends"
output: html_document
Author: Rajiv Basnet
---

```{r, results='hide', message=FALSE}
library(tidyverse)
library(dplyr)
library(modelr)
library(scales)
library(lubridate)
library(stats)
```

```{r, results="hide"}
set.seed(42)

data <- read.csv("Autos/Autos/merged.csv") %>% mutate(Period = as.Date(Period))
data <- data %>% mutate(sales = log(sales))
data

```

```{r}
#our models
model_baseline <- lm(sales~lag(sales,1)+lag(sales,12), data=data)
summary(model_baseline)

model_with_trends <- lm(sales~lag(sales,1)+lag(sales,12) + suvs + insurance, data=data)
summary(model_with_trends)
```

```{r}
#add predictions with both models (Without Rolling Window)s
data_with_pred <- data %>%
  add_predictions(model_baseline, var ="base") %>% 
  add_predictions(model_with_trends, var ="trends") %>%
  filter(Period >= as.Date('2005-06-01')) %>%
  rename(actual = sales)

head(data_with_pred)
```


```{r}
#visualizations (Without Rolling Window)

data_with_pred %>% 
  pivot_longer(c("actual", "base", "trends"), names_to = "sales_type", values_to = "num_of_sales") %>%
  ggplot(aes(x = Period, y = num_of_sales, group = sales_type, color = sales_type)) +
  geom_line(aes(y = num_of_sales, color = sales_type, linetype= sales_type)) +
  scale_color_manual(values=c("black", "red", "darkgray")) +
  scale_linetype_manual(values=c("solid", "dashed", "solid")) +
  labs(x = "Date", y = "Log of Sales")
```
```{r}
#MAE calculation (Without Rolling Window)

base_mae <- mae(model_baseline, data)
trends_mae <- mae(model_with_trends, data)

base_mae
trends_mae

```

```{r, results="hide"}

#Implementation of Rolling Window

all_data <- data %>% 
  rename(actual = sales) %>%
  mutate(baseline = NA, trends = NA) %>%
  mutate(lag1 = lag(actual, 1), lag12 = lag(actual, 12))

head(all_data)

K <- 17
num_rows <- nrow(all_data)


for (k in K: (num_rows -1) ) {
  model1 <- lm(actual ~ lag1 + lag12, data = all_data[1:k, ])
  model2 <- lm(actual ~ lag1 + lag12 + suvs + insurance, data = all_data[1:k, ])
  all_data$baseline[k + 1] <- predict(model1, all_data[k + 1,])
  all_data$trends[k + 1] <- predict(model2, all_data[k + 1,])
}

all_data
```

```{r}
#Visualization (With Rolling Window)

all_data %>% 
  pivot_longer(c("actual", "baseline", "trends"), names_to = "sales_type", values_to = "num_of_sales") %>%
  ggplot(aes(x = Period, y = num_of_sales, group = sales_type, color = sales_type)) +
  geom_line(aes(y = num_of_sales, color = sales_type, linetype= sales_type)) +
  scale_color_manual(values=c("black", "red", "darkgray")) +
  scale_linetype_manual(values=c("solid", "dashed", "solid")) +
  labs(x = "Date", y = "Log of Sales")
```
```{r}
#MAE Calculation (With Rolling Window)

mae_baseline <- sum(abs(all_data$actual - all_data$baseline), na.rm = TRUE)/(num_rows - 17)
mae_trends <- sum(abs(all_data$actual - all_data$trends), na.rm = TRUE)/(num_rows - 17)

mae_baseline
mae_trends

```

MAE Baseline is `r mae_baseline`
and MAE With Trends is `r mae_trends`

The graph and MAE's match excatly as in the paper. 
Thus, it is reproducible.

