---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=26
ratings %>% 
  ggplot(aes(x = rating)) +
  geom_histogram(bins = 10) +
  scale_y_continuous(label = comma) +
  labs(x = "Rating", y = "Number of Ratings")

```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings
# hint: use the n() function for easy counting within a group

ratings %>% 
  group_by(movie_id) %>%
  summarize(mean_rating = mean(rating), num_of_ratings = n())
```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis
ratings %>% 
  group_by(movie_id) %>%
  summarise(num_of_ratings = n()) %>%
  ggplot(aes(x = num_of_ratings)) +
  scale_x_log10() + 
  geom_histogram(bins = 50) +
  labs(x = "Number of Ratings", y = "Number of Movies")
```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=28
# hint: try geom_histogram and geom_density

ratings %>% 
  group_by(movie_id) %>%
  summarise(mean_rating = mean(rating)) %>%
  ggplot(aes(x = mean_rating)) +
  geom_histogram(bins = 10) + 
  labs(x = "Movie Id", y = "Mean Rating")
  
ratings %>% 
  group_by(movie_id) %>%
  summarise(mean_rating = mean(rating)) %>%
  ggplot(aes(x = mean_rating)) +
  geom_density(fill = "grey") + 
  labs(x = "Mean Rating", y = "Number of Movies")

```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=30
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

# plot the CDF of movie popularity

cdf_movie <- ratings %>% 
  group_by(movie_id) %>%
  summarize(num_of_ratings = n()) %>%
  arrange(desc(num_of_ratings)) %>%
  mutate(rank = row_number()) %>%
  mutate(cdf = cumsum(num_of_ratings)/sum(num_of_ratings) * 100) 

cdf_movie %>%
  ggplot(aes(x = rank, y = cdf)) +
  geom_line() + 
  labs(x = "Movie Rank", y = "CDF")
```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
user_by_num_ratings <- ratings %>% 
  group_by(user_id) %>%
  summarize(mean_rating_by_user = mean(rating), num_rating_user = n())

user_by_num_ratings
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
ratings %>% 
  group_by(user_id) %>%
  summarize(mean_rating_by_user = mean(rating), num_rating_by_user = n()) %>%
  ggplot(aes(x = num_rating_by_user)) +
  geom_histogram(bins = 50) + 
  scale_x_log10() +
  labs(x = "Number of Ratings", y = "Number of Users")
  
```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).

user_num_ratings_10 <- filter(user_by_num_ratings, num_rating_user >= 10)
ratings_table_10 <- left_join(ratings, user_num_ratings_10, by = "user_id")
new_ratings_table <- left_join(ratings_table_10, cdf_movie, by = "movie_id")


#for 100% satisfaction
satisfaction_100 <- new_ratings_table %>% 
  group_by(user_id) %>%
  summarize(user_s100 = max(rank)) %>%
  arrange(user_s100) %>%
  select(user_id, user_s100) %>% 
  group_by(user_s100) %>%
  summarize(count = n()) %>%
  mutate(cdf = cumsum(count)/sum(count))

#for 90% satisfaction
satisfaction_90 <- new_ratings_table %>% 
  group_by(user_id) %>%
  summarize(user_s90 = quantile(rank, 0.9)) %>%
  arrange(user_s90) %>%
  select(user_id, user_s90) %>% 
  group_by(user_s90) %>%
  summarize(count = n()) %>%
  mutate(cdf = cumsum(count)/sum(count))


ggplot() +
  geom_line(data = satisfaction_100, aes(x = user_s100, y = cdf)) +
   geom_line(data = satisfaction_90, aes(x = user_s90, y = cdf)) +
  labs(x = "Inventory Size", y = "Percent of user satisfied")
  


```
